# Generated by Django 5.2.4 on 2025-08-22 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0016_m3uaccount_priority'),
        ('vod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M3UVODCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Set to false to deactivate this category for the M3U account')),
                ('custom_properties', models.JSONField(blank=True, help_text='Provider-specific data like quality, language, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m3u_relations', to='vod.vodcategory')),
                ('m3u_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relations', to='m3u.m3uaccount')),
            ],
            options={
                'verbose_name': 'M3U VOD Category Relation',
                'verbose_name_plural': 'M3U VOD Category Relations',
                'unique_together': {('m3u_account', 'category')},
            },
        ),
    ]
