# Generated by Django A.I. on 2025-08-09
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='custom_properties',
            field=models.JSONField(blank=True, null=True, help_text='Custom properties for this episode'),
        ),
    ]
