# Generated by Django 5.1.6 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='custom_properties',
            field=models.JSONField(blank=True, help_text='Additional metadata and properties for the movie', null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='custom_properties',
            field=models.JSONField(blank=True, help_text='Additional metadata and properties for the series', null=True),
        ),
    ]
