# Generated by Django A.I. on 2025-08-09
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0002_episode_custom_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='duration',
            new_name='duration_secs',
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_secs',
            field=models.IntegerField(blank=True, null=True, help_text='Duration in seconds'),
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='duration',
            new_name='duration_secs',
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration_secs',
            field=models.IntegerField(blank=True, null=True, help_text='Duration in seconds'),
        ),
    ]
