# Generated by Django 5.2.4 on 2025-08-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0002_movie_series_custom_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='release_date',
            new_name='air_date',
        ),
    ]
