# Generated by Django 5.2.4 on 2025-08-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0023_stream_stream_stats_stream_stream_stats_updated_at'),
        ('vod', '0003_duration_secs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='IMDB ID for metadata', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(blank=True, help_text='TMDB ID for metadata', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='IMDB ID for metadata', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tmdb_id',
            field=models.CharField(blank=True, help_text='TMDB ID for metadata', max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', True), ('imdb_id__isnull', True)), fields=('name', 'year'), name='unique_movie_name_year_no_external_id'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', True), ('imdb_id__isnull', True)), fields=('name', 'year'), name='unique_series_name_year_no_external_id'),
        ),
    ]
