# Generated by Django 5.2.4 on 2025-08-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0004_alter_movie_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m3umovierelation',
            name='url',
        ),
    ]
